version: "3"
services:
  ccpoints:
    image: node:latest
    volumes:
     - .:/app
    restart: always
    working_dir: /app/src
    command: "bash -c 'yarn && yarn watch'"
    ports:
     - 3000:3000
    environment:
      - SESSION_SECRET=changeme
      - CLASH_API_TOKEN=changeme
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./src/migrations:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=ccpoints
      - POSTGRES_USER=ccpoints
      - POSTGRES_PASSWORD=ccpoints
