version: "3"
services:
  fwapoints:
    image: node:latest
    volumes:
     - ./src:/app/src
     - ./logs:/app/logs
    restart: always
    working_dir: /app/src
    entrypoint: "yarn start"
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fwapoints
      - POSTGRES_USER=fwapoints
      - POSTGRES_PASSWORD=fwapoints

# nginx network managed externally
networks:
  default:
    external:
      name: nginx
