version: "3"
services:
  ccpoints:
    image: node:latest
    volumes:
     - .:/app
    networks:
     - default
     - nginx
    restart: always
    working_dir: /app/src
    entrypoint: "yarn start"
    environment:
      - SESSION_SECRET=changeme
      - CLASH_API_TOKEN=changeme
      - HEALTHCHECK_URL=changeme
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./src/migrations:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=ccpoints
      - POSTGRES_USER=ccpoints
      - POSTGRES_PASSWORD=ccpoints

# nginx network is managed externally on kuilin's server
# forwards incoming requests to ccpoints_ccpoints_1:3000 inside docker network
# your setup may vary of course
networks:
  nginx:
    external: true
